### ISSUE TITLE
Ash spritesheet is copyrighted

### ISSUE THREAD

**Issue by davcri** [crystal-bit/godot-tutorials#1]
I want to use only free to use & redistribute content in this repository. 

Can anyone find a replacement for the Ash spritesheet and make a PR to fix the [input-mapping tutorial](https://github.com/crystal-bit/godot-tutorials/tree/master/tutorials/input-mapping) ?

**Comment by Hairic95** [comment]
If you like them feel free to use, they are kinda simple but I made them for Ludum Dare 43.


![cultist1_down](https://user-images.githubusercontent.com/22881226/51562151-6bd53b00-1e89-11e9-875b-9f9fae758e53.png)
![cultist1_left](https://user-images.githubusercontent.com/22881226/51562153-6bd53b00-1e89-11e9-9791-ee7851aa8462.png)
![cultist1_right](https://user-images.githubusercontent.com/22881226/51562155-6bd53b00-1e89-11e9-8a83-434ca2abcc63.png)
![cultist1_up](https://user-images.githubusercontent.com/22881226/51562156-6bd53b00-1e89-11e9-8050-21b689c28f6b.png)

**Comment by davcri** [comment]
Hi @Hairic95 !  
Thank you very much for this quick answer and for these sprites. They look good to me!

I would like you to upload the files, so that you will be listed in the [contributors page](https://github.com/crystal-bit/godot-tutorials/graphs/contributors).  
Can you upload the spritesheets in the [`tutorials/input-mapping/Character/spritesheet`](https://github.com/crystal-bit/godot-tutorials/tree/master/tutorials/input-mapping/Character/spritesheet) folder?   

You can use the web interface (instructions [here](https://help.github.com/articles/adding-a-file-to-a-repository/)).

**Comment by davcri** [comment]
I accepted the [pull request](https://github.com/crystal-bit/godot-tutorials/pull/2) and now you appear in the list of contributors :100: 
https://github.com/crystal-bit/godot-tutorials/graphs/contributors

With the last commit (https://github.com/crystal-bit/godot-tutorials/commit/c357ae2d1225cf73a614c987aeea6378c37f21ee) I also replaced the sprites in the project! 

![image](https://user-images.githubusercontent.com/6860637/51623804-ccbc4c00-1f39-11e9-8e1a-038c023ce2c9.png)

---

PS: I'm leaving this issue opened for this week (just for who still didn't see the video about this GitHub organization)
